const GI_DATABASE=[
{n:"White rice (cooked)",cat:"Grains",gi:73,gl:29,serv:"150g"},
{n:"Brown rice (cooked)",cat:"Grains",gi:68,gl:16,serv:"150g"},
{n:"Basmati rice (cooked)",cat:"Grains",gi:58,gl:18,serv:"150g"},
{n:"Cooled / reheated white rice",cat:"Grains",gi:54,gl:18,serv:"150g"},
{n:"Jasmine rice",cat:"Grains",gi:89,gl:35,serv:"150g"},
{n:"Wild rice (cooked)",cat:"Grains",gi:57,gl:18,serv:"150g"},
{n:"Black rice (cooked)",cat:"Grains",gi:42,gl:13,serv:"150g"},
{n:"Red rice (cooked)",cat:"Grains",gi:55,gl:17,serv:"150g"},
{n:"Quinoa (cooked)",cat:"Grains",gi:53,gl:13,serv:"150g"},
{n:"Amaranth (cooked)",cat:"Grains",gi:35,gl:11,serv:"100g"},
{n:"Buckwheat (cooked)",cat:"Grains",gi:51,gl:11,serv:"150g"},
{n:"Millet / bajra (cooked)",cat:"Grains",gi:71,gl:26,serv:"150g"},
{n:"Bajra roti (pearl millet)",cat:"Grains",gi:55,gl:9,serv:"1 medium"},
{n:"Jowar roti (sorghum)",cat:"Grains",gi:51,gl:8,serv:"1 medium"},
{n:"Ragi / finger millet porridge",cat:"Grains",gi:47,gl:9,serv:"1 bowl"},
{n:"Ragi dosa",cat:"Grains",gi:55,gl:12,serv:"1 medium"},
{n:"Ragi mudde",cat:"Grains",gi:50,gl:10,serv:"1 piece"},
{n:"White bread",cat:"Grains",gi:75,gl:11,serv:"1 slice (30g)"},
{n:"Whole wheat bread",cat:"Grains",gi:69,gl:9,serv:"1 slice (30g)"},
{n:"Sourdough bread",cat:"Grains",gi:54,gl:8,serv:"1 slice (30g)"},
{n:"Rye bread",cat:"Grains",gi:50,gl:6,serv:"1 slice (30g)"},
{n:"Multigrain bread",cat:"Grains",gi:48,gl:7,serv:"1 slice (30g)"},
{n:"Naan bread",cat:"Grains",gi:71,gl:24,serv:"1 piece (90g)"},
{n:"Chapati / roti (whole wheat)",cat:"Grains",gi:52,gl:10,serv:"1 medium"},
{n:"Paratha (plain)",cat:"Grains",gi:66,gl:16,serv:"1 medium"},
{n:"Puri (fried)",cat:"Grains",gi:69,gl:15,serv:"2 small"},
{n:"Bhatura",cat:"Grains",gi:74,gl:20,serv:"1 medium"},
{n:"Pasta (white, al dente)",cat:"Grains",gi:49,gl:18,serv:"180g"},
{n:"Pasta (white, overcooked)",cat:"Grains",gi:61,gl:22,serv:"180g"},
{n:"Pasta (whole wheat)",cat:"Grains",gi:42,gl:16,serv:"180g"},
{n:"Pasta (lentil / chickpea)",cat:"Grains",gi:30,gl:11,serv:"180g"},
{n:"Noodles (instant / Maggi)",cat:"Grains",gi:73,gl:20,serv:"1 packet"},
{n:"Rice noodles",cat:"Grains",gi:61,gl:23,serv:"180g"},
{n:"Glass noodles (mung bean)",cat:"Grains",gi:39,gl:14,serv:"180g"},
{n:"Couscous",cat:"Grains",gi:65,gl:23,serv:"150g"},
{n:"Bulgur wheat (cooked)",cat:"Grains",gi:48,gl:12,serv:"150g"},
{n:"Freekeh (cooked)",cat:"Grains",gi:43,gl:11,serv:"150g"},
{n:"Barley (cooked)",cat:"Grains",gi:28,gl:8,serv:"150g"},
{n:"Oats (rolled, cooked)",cat:"Grains",gi:55,gl:13,serv:"1 bowl"},
{n:"Steel-cut oats",cat:"Grains",gi:42,gl:11,serv:"1 bowl"},
{n:"Instant oatmeal",cat:"Grains",gi:79,gl:21,serv:"1 bowl"},
{n:"Oat bran (cooked)",cat:"Grains",gi:50,gl:9,serv:"50g"},
{n:"Cornflakes",cat:"Grains",gi:81,gl:21,serv:"30g"},
{n:"Muesli (no added sugar)",cat:"Grains",gi:57,gl:10,serv:"30g"},
{n:"Bran flakes",cat:"Grains",gi:74,gl:13,serv:"30g"},
{n:"All-Bran",cat:"Grains",gi:55,gl:12,serv:"30g"},
{n:"Idli",cat:"Grains",gi:70,gl:15,serv:"2 pieces"},
{n:"Dosa (plain)",cat:"Grains",gi:77,gl:18,serv:"1 medium"},
{n:"Set dosa",cat:"Grains",gi:65,gl:14,serv:"2 small"},
{n:"Upma (semolina)",cat:"Grains",gi:65,gl:13,serv:"1 bowl"},
{n:"Vermicelli upma",cat:"Grains",gi:70,gl:16,serv:"1 bowl"},
{n:"Poha (flattened rice)",cat:"Grains",gi:67,gl:18,serv:"1 bowl"},
{n:"Khichdi (rice + moong dal)",cat:"Grains",gi:48,gl:13,serv:"1 bowl"},
{n:"Khichdi (rice + toor dal)",cat:"Grains",gi:52,gl:15,serv:"1 bowl"},
{n:"Semolina / rava (dry)",cat:"Grains",gi:60,gl:28,serv:"50g"},
{n:"Tortilla (corn)",cat:"Grains",gi:46,gl:10,serv:"2 small"},
{n:"Tortilla (flour)",cat:"Grains",gi:55,gl:13,serv:"1 medium"},
{n:"Rice cakes",cat:"Grains",gi:82,gl:17,serv:"2 cakes"},
{n:"Bagel (plain)",cat:"Grains",gi:72,gl:25,serv:"1 medium"},
{n:"Croissant",cat:"Grains",gi:67,gl:17,serv:"1 medium"},
{n:"Pita bread (white)",cat:"Grains",gi:68,gl:10,serv:"1 piece"},
{n:"Pita bread (whole wheat)",cat:"Grains",gi:57,gl:8,serv:"1 piece"},
{n:"Crackers (water biscuits)",cat:"Grains",gi:65,gl:11,serv:"5 crackers"},
{n:"Oatcakes",cat:"Grains",gi:55,gl:8,serv:"2 pieces"},
{n:"Dhokla",cat:"Grains",gi:35,gl:8,serv:"3 pieces"},
{n:"Thepla",cat:"Grains",gi:54,gl:11,serv:"1 medium"},
{n:"Chickpeas / chana (boiled)",cat:"Legumes",gi:28,gl:8,serv:"150g"},
{n:"Kala chana (black chickpea, boiled)",cat:"Legumes",gi:25,gl:6,serv:"150g"},
{n:"Kidney beans / rajma (boiled)",cat:"Legumes",gi:24,gl:6,serv:"150g"},
{n:"Black beans (boiled)",cat:"Legumes",gi:30,gl:7,serv:"150g"},
{n:"Lentils / masoor dal (boiled)",cat:"Legumes",gi:29,gl:5,serv:"150g"},
{n:"Moong dal (boiled)",cat:"Legumes",gi:25,gl:4,serv:"150g"},
{n:"Moong dal (sprouted)",cat:"Legumes",gi:22,gl:3,serv:"100g"},
{n:"Toor / arhar dal (boiled)",cat:"Legumes",gi:29,gl:5,serv:"150g"},
{n:"Urad dal (boiled)",cat:"Legumes",gi:32,gl:7,serv:"150g"},
{n:"Chana dal (boiled)",cat:"Legumes",gi:11,gl:3,serv:"150g"},
{n:"Soybeans (boiled)",cat:"Legumes",gi:16,gl:1,serv:"150g"},
{n:"Green peas (boiled)",cat:"Legumes",gi:51,gl:4,serv:"80g"},
{n:"Baked beans (canned)",cat:"Legumes",gi:48,gl:7,serv:"150g"},
{n:"Hummus",cat:"Legumes",gi:6,gl:1,serv:"2 tbsp"},
{n:"Edamame",cat:"Legumes",gi:18,gl:2,serv:"100g"},
{n:"Tofu",cat:"Legumes",gi:15,gl:1,serv:"100g"},
{n:"Tempeh",cat:"Legumes",gi:15,gl:1,serv:"100g"},
{n:"Black-eyed peas / lobia (boiled)",cat:"Legumes",gi:33,gl:7,serv:"150g"},
{n:"Dal makhani",cat:"Legumes",gi:38,gl:10,serv:"1 bowl"},
{n:"Rajma curry",cat:"Legumes",gi:28,gl:8,serv:"1 bowl"},
{n:"Chole / chana masala",cat:"Legumes",gi:30,gl:9,serv:"1 bowl"},
{n:"Sambar",cat:"Legumes",gi:30,gl:6,serv:"1 bowl"},
{n:"Apple",cat:"Fruits",gi:36,gl:5,serv:"1 medium"},
{n:"Banana (ripe)",cat:"Fruits",gi:51,gl:12,serv:"1 medium"},
{n:"Banana (under-ripe / green)",cat:"Fruits",gi:30,gl:7,serv:"1 medium"},
{n:"Orange",cat:"Fruits",gi:43,gl:5,serv:"1 medium"},
{n:"Orange juice (no sugar)",cat:"Fruits",gi:50,gl:12,serv:"250ml"},
{n:"Grapes (green)",cat:"Fruits",gi:46,gl:7,serv:"120g"},
{n:"Grapes (red / black)",cat:"Fruits",gi:59,gl:9,serv:"120g"},
{n:"Watermelon",cat:"Fruits",gi:76,gl:8,serv:"150g"},
{n:"Mango",cat:"Fruits",gi:51,gl:8,serv:"100g"},
{n:"Pineapple",cat:"Fruits",gi:59,gl:7,serv:"120g"},
{n:"Papaya",cat:"Fruits",gi:60,gl:8,serv:"120g"},
{n:"Pear",cat:"Fruits",gi:38,gl:4,serv:"1 medium"},
{n:"Peach",cat:"Fruits",gi:42,gl:5,serv:"1 medium"},
{n:"Plum",cat:"Fruits",gi:39,gl:5,serv:"2 medium"},
{n:"Strawberries",cat:"Fruits",gi:40,gl:1,serv:"150g"},
{n:"Blueberries",cat:"Fruits",gi:53,gl:5,serv:"150g"},
{n:"Raspberries",cat:"Fruits",gi:32,gl:2,serv:"150g"},
{n:"Blackberries",cat:"Fruits",gi:25,gl:2,serv:"150g"},
{n:"Cherries",cat:"Fruits",gi:22,gl:3,serv:"120g"},
{n:"Guava",cat:"Fruits",gi:24,gl:2,serv:"1 medium"},
{n:"Kiwi",cat:"Fruits",gi:50,gl:6,serv:"1 medium"},
{n:"Dates (Medjool fresh)",cat:"Fruits",gi:42,gl:18,serv:"4 pieces"},
{n:"Dates (dried)",cat:"Fruits",gi:46,gl:22,serv:"4 pieces"},
{n:"Raisins",cat:"Fruits",gi:64,gl:28,serv:"60g"},
{n:"Dried apricots",cat:"Fruits",gi:32,gl:9,serv:"60g"},
{n:"Dried cranberries",cat:"Fruits",gi:62,gl:23,serv:"40g"},
{n:"Prunes (dried plum)",cat:"Fruits",gi:29,gl:10,serv:"60g"},
{n:"Figs (fresh)",cat:"Fruits",gi:35,gl:5,serv:"2 medium"},
{n:"Figs (dried)",cat:"Fruits",gi:61,gl:16,serv:"60g"},
{n:"Pomegranate",cat:"Fruits",gi:53,gl:9,serv:"1 medium"},
{n:"Pomegranate juice",cat:"Fruits",gi:53,gl:12,serv:"200ml"},
{n:"Apricot (fresh)",cat:"Fruits",gi:34,gl:3,serv:"3 medium"},
{n:"Cantaloupe / muskmelon",cat:"Fruits",gi:65,gl:5,serv:"120g"},
{n:"Lychee",cat:"Fruits",gi:57,gl:8,serv:"10 pieces"},
{n:"Jackfruit (ripe)",cat:"Fruits",gi:75,gl:14,serv:"100g"},
{n:"Jackfruit (raw / kathal sabzi)",cat:"Fruits",gi:50,gl:9,serv:"100g"},
{n:"Custard apple / sitaphal",cat:"Fruits",gi:54,gl:11,serv:"100g"},
{n:"Sapota / chikoo",cat:"Fruits",gi:58,gl:14,serv:"2 medium"},
{n:"Jamun / Indian blackberry",cat:"Fruits",gi:25,gl:3,serv:"100g"},
{n:"Amla / Indian gooseberry",cat:"Fruits",gi:15,gl:1,serv:"3 pieces"},
{n:"Tamarind",cat:"Fruits",gi:23,gl:8,serv:"20g"},
{n:"Avocado",cat:"Fruits",gi:15,gl:1,serv:"100g"},
{n:"Coconut (fresh flesh)",cat:"Fruits",gi:45,gl:2,serv:"50g"},
{n:"Apple juice (no sugar)",cat:"Fruits",gi:41,gl:12,serv:"250ml"},
{n:"Mango juice (packaged)",cat:"Fruits",gi:55,gl:16,serv:"250ml"},
{n:"Tomato juice",cat:"Fruits",gi:38,gl:4,serv:"250ml"},
{n:"Potato (boiled)",cat:"Vegetables",gi:78,gl:18,serv:"150g"},
{n:"Potato (baked)",cat:"Vegetables",gi:85,gl:26,serv:"150g"},
{n:"Potato (mashed)",cat:"Vegetables",gi:87,gl:17,serv:"150g"},
{n:"Sweet potato (boiled)",cat:"Vegetables",gi:63,gl:17,serv:"150g"},
{n:"Sweet potato (baked)",cat:"Vegetables",gi:70,gl:22,serv:"150g"},
{n:"French fries",cat:"Vegetables",gi:75,gl:22,serv:"150g"},
{n:"Aloo sabzi (potato curry)",cat:"Vegetables",gi:72,gl:16,serv:"1 bowl"},
{n:"Carrot (raw)",cat:"Vegetables",gi:16,gl:1,serv:"80g"},
{n:"Carrot (boiled)",cat:"Vegetables",gi:39,gl:2,serv:"80g"},
{n:"Beetroot (boiled)",cat:"Vegetables",gi:64,gl:6,serv:"80g"},
{n:"Corn / maize (sweet, boiled)",cat:"Vegetables",gi:52,gl:9,serv:"90g"},
{n:"Pumpkin (boiled)",cat:"Vegetables",gi:75,gl:3,serv:"80g"},
{n:"Tomato (fresh)",cat:"Vegetables",gi:15,gl:1,serv:"1 medium"},
{n:"Broccoli",cat:"Vegetables",gi:15,gl:1,serv:"80g"},
{n:"Spinach / palak",cat:"Vegetables",gi:15,gl:0,serv:"80g"},
{n:"Cauliflower",cat:"Vegetables",gi:15,gl:1,serv:"80g"},
{n:"Cabbage",cat:"Vegetables",gi:10,gl:0,serv:"80g"},
{n:"Lauki / bottle gourd",cat:"Vegetables",gi:15,gl:1,serv:"100g"},
{n:"Tinda / round gourd",cat:"Vegetables",gi:15,gl:1,serv:"100g"},
{n:"Karela / bitter gourd",cat:"Vegetables",gi:14,gl:1,serv:"100g"},
{n:"Turai / ridge gourd",cat:"Vegetables",gi:15,gl:1,serv:"100g"},
{n:"Drumstick / moringa pods",cat:"Vegetables",gi:20,gl:1,serv:"100g"},
{n:"Bell pepper / capsicum",cat:"Vegetables",gi:15,gl:1,serv:"80g"},
{n:"Cucumber",cat:"Vegetables",gi:15,gl:0,serv:"100g"},
{n:"Onion (raw)",cat:"Vegetables",gi:10,gl:1,serv:"50g"},
{n:"Mushroom",cat:"Vegetables",gi:10,gl:0,serv:"80g"},
{n:"Green beans",cat:"Vegetables",gi:30,gl:1,serv:"80g"},
{n:"Okra / bhindi",cat:"Vegetables",gi:20,gl:1,serv:"80g"},
{n:"Eggplant / baingan",cat:"Vegetables",gi:15,gl:1,serv:"80g"},
{n:"Courgette / zucchini",cat:"Vegetables",gi:15,gl:0,serv:"80g"},
{n:"Asparagus",cat:"Vegetables",gi:15,gl:0,serv:"80g"},
{n:"Kale",cat:"Vegetables",gi:15,gl:0,serv:"80g"},
{n:"Garlic",cat:"Vegetables",gi:30,gl:1,serv:"1 clove"},
{n:"Ginger (fresh)",cat:"Vegetables",gi:15,gl:0,serv:"10g"},
{n:"Yam / suran (boiled)",cat:"Vegetables",gi:54,gl:10,serv:"150g"},
{n:"Arbi / taro (boiled)",cat:"Vegetables",gi:56,gl:9,serv:"100g"},
{n:"Plantain (boiled / green)",cat:"Vegetables",gi:40,gl:9,serv:"120g"},
{n:"Radish / mooli",cat:"Vegetables",gi:15,gl:0,serv:"80g"},
{n:"Spring onion / scallion",cat:"Vegetables",gi:10,gl:0,serv:"30g"},
{n:"Peas (frozen, boiled)",cat:"Vegetables",gi:48,gl:4,serv:"80g"},
{n:"Palak paneer",cat:"Vegetables",gi:20,gl:3,serv:"1 bowl"},
{n:"Aloo gobi (potato + cauliflower)",cat:"Vegetables",gi:55,gl:10,serv:"1 bowl"},
{n:"Baingan bharta",cat:"Vegetables",gi:20,gl:2,serv:"1 bowl"},
{n:"Whole milk",cat:"Dairy",gi:31,gl:4,serv:"250ml"},
{n:"Skim milk",cat:"Dairy",gi:32,gl:4,serv:"250ml"},
{n:"Full-fat dahi / curd (plain)",cat:"Dairy",gi:14,gl:1,serv:"150g"},
{n:"Greek yogurt (plain)",cat:"Dairy",gi:11,gl:1,serv:"150g"},
{n:"Flavoured yogurt (sweetened)",cat:"Dairy",gi:41,gl:10,serv:"150g"},
{n:"Shrikhand",cat:"Dairy",gi:48,gl:14,serv:"100g"},
{n:"Kheer / rice pudding",cat:"Dairy",gi:60,gl:14,serv:"100g"},
{n:"Ice cream (full-fat, vanilla)",cat:"Dairy",gi:51,gl:8,serv:"65g"},
{n:"Paneer (fresh)",cat:"Dairy",gi:14,gl:1,serv:"100g"},
{n:"Paneer tikka",cat:"Dairy",gi:18,gl:2,serv:"6 pieces"},
{n:"Cheese (cheddar)",cat:"Dairy",gi:0,gl:0,serv:"30g"},
{n:"Ghee",cat:"Dairy",gi:0,gl:0,serv:"1 tbsp"},
{n:"Butter",cat:"Dairy",gi:0,gl:0,serv:"1 tbsp"},
{n:"Soy milk (unsweetened)",cat:"Dairy",gi:34,gl:4,serv:"250ml"},
{n:"Almond milk (unsweetened)",cat:"Dairy",gi:25,gl:1,serv:"250ml"},
{n:"Oat milk",cat:"Dairy",gi:69,gl:9,serv:"250ml"},
{n:"Buttermilk / chaas (salted)",cat:"Dairy",gi:15,gl:1,serv:"250ml"},
{n:"Lassi (sweet)",cat:"Dairy",gi:48,gl:14,serv:"250ml"},
{n:"Lassi (salted)",cat:"Dairy",gi:15,gl:1,serv:"250ml"},
{n:"Raita (dahi + cucumber)",cat:"Dairy",gi:14,gl:1,serv:"100g"},
{n:"Almonds (raw)",cat:"Nuts & Seeds",gi:0,gl:0,serv:"30g"},
{n:"Walnuts",cat:"Nuts & Seeds",gi:15,gl:1,serv:"30g"},
{n:"Cashews (raw)",cat:"Nuts & Seeds",gi:25,gl:3,serv:"30g"},
{n:"Peanuts (dry roasted)",cat:"Nuts & Seeds",gi:14,gl:1,serv:"30g"},
{n:"Pistachios",cat:"Nuts & Seeds",gi:15,gl:1,serv:"30g"},
{n:"Macadamia nuts",cat:"Nuts & Seeds",gi:10,gl:0,serv:"30g"},
{n:"Brazil nuts",cat:"Nuts & Seeds",gi:10,gl:0,serv:"30g"},
{n:"Peanut butter (natural)",cat:"Nuts & Seeds",gi:14,gl:1,serv:"2 tbsp"},
{n:"Almond butter",cat:"Nuts & Seeds",gi:8,gl:0,serv:"2 tbsp"},
{n:"Chia seeds",cat:"Nuts & Seeds",gi:1,gl:0,serv:"15g"},
{n:"Flaxseeds / alsi (ground)",cat:"Nuts & Seeds",gi:35,gl:1,serv:"15g"},
{n:"Pumpkin seeds / kaddu ke beej",cat:"Nuts & Seeds",gi:25,gl:1,serv:"30g"},
{n:"Sunflower seeds",cat:"Nuts & Seeds",gi:35,gl:1,serv:"30g"},
{n:"Sesame seeds / til",cat:"Nuts & Seeds",gi:35,gl:1,serv:"15g"},
{n:"Methi / fenugreek seeds",cat:"Nuts & Seeds",gi:5,gl:0,serv:"5g"},
{n:"Sabja / basil seeds",cat:"Nuts & Seeds",gi:2,gl:0,serv:"10g"},
{n:"Makhana / fox nuts (roasted)",cat:"Nuts & Seeds",gi:14,gl:2,serv:"30g"},
{n:"Coconut (desiccated)",cat:"Nuts & Seeds",gi:42,gl:2,serv:"30g"},
{n:"Chicken breast (grilled)",cat:"Protein",gi:0,gl:0,serv:"100g"},
{n:"Eggs (whole, boiled)",cat:"Protein",gi:0,gl:0,serv:"2 eggs"},
{n:"Fish (salmon, grilled)",cat:"Protein",gi:0,gl:0,serv:"100g"},
{n:"Fish (tuna, in water)",cat:"Protein",gi:0,gl:0,serv:"100g"},
{n:"Fish (rohu / katla, Indian)",cat:"Protein",gi:0,gl:0,serv:"100g"},
{n:"Shrimp / prawns",cat:"Protein",gi:0,gl:0,serv:"100g"},
{n:"Beef (lean, grilled)",cat:"Protein",gi:0,gl:0,serv:"100g"},
{n:"Mutton / lamb (cooked)",cat:"Protein",gi:0,gl:0,serv:"100g"},
{n:"Soy chunks / nutrela (cooked)",cat:"Protein",gi:20,gl:2,serv:"30g dry"},
{n:"Protein powder (whey, unflavoured)",cat:"Protein",gi:30,gl:2,serv:"30g scoop"},
{n:"Water (plain)",cat:"Beverages",gi:0,gl:0,serv:"any"},
{n:"Black coffee (no sugar)",cat:"Beverages",gi:0,gl:0,serv:"1 cup"},
{n:"Green tea (no sugar)",cat:"Beverages",gi:0,gl:0,serv:"1 cup"},
{n:"Masala chai (with sugar)",cat:"Beverages",gi:35,gl:6,serv:"1 cup"},
{n:"Masala chai (no sugar)",cat:"Beverages",gi:0,gl:0,serv:"1 cup"},
{n:"Jeera / cumin water",cat:"Beverages",gi:0,gl:0,serv:"1 glass"},
{n:"Haldi doodh / golden milk",cat:"Beverages",gi:28,gl:3,serv:"1 cup"},
{n:"Coconut water (fresh)",cat:"Beverages",gi:54,gl:5,serv:"250ml"},
{n:"Beer (lager)",cat:"Beverages",gi:66,gl:4,serv:"250ml"},
{n:"Red wine",cat:"Beverages",gi:0,gl:0,serv:"150ml"},
{n:"Cola / soft drink",cat:"Beverages",gi:63,gl:16,serv:"250ml"},
{n:"Diet cola (zero sugar)",cat:"Beverages",gi:0,gl:0,serv:"250ml"},
{n:"Sports drink (Gatorade type)",cat:"Beverages",gi:78,gl:13,serv:"250ml"},
{n:"Energy drink (Red Bull type)",cat:"Beverages",gi:73,gl:17,serv:"250ml"},
{n:"Smoothie (banana + milk)",cat:"Beverages",gi:58,gl:16,serv:"300ml"},
{n:"Table sugar / sucrose",cat:"Sweets",gi:65,gl:7,serv:"1 tbsp"},
{n:"Honey",cat:"Sweets",gi:61,gl:12,serv:"1 tbsp"},
{n:"Jaggery / gur",cat:"Sweets",gi:84,gl:18,serv:"20g"},
{n:"Maple syrup",cat:"Sweets",gi:54,gl:10,serv:"1 tbsp"},
{n:"Agave syrup",cat:"Sweets",gi:17,gl:6,serv:"1 tbsp"},
{n:"Stevia (pure)",cat:"Sweets",gi:0,gl:0,serv:"any"},
{n:"Dark chocolate (70%+)",cat:"Sweets",gi:23,gl:4,serv:"30g"},
{n:"Dark chocolate (85%+)",cat:"Sweets",gi:20,gl:3,serv:"30g"},
{n:"Milk chocolate",cat:"Sweets",gi:50,gl:12,serv:"30g"},
{n:"White chocolate",cat:"Sweets",gi:44,gl:13,serv:"30g"},
{n:"Cookies / biscuits (plain)",cat:"Sweets",gi:64,gl:10,serv:"2 pieces"},
{n:"Marie biscuits",cat:"Sweets",gi:62,gl:9,serv:"3 pieces"},
{n:"Cake (sponge, plain)",cat:"Sweets",gi:53,gl:17,serv:"1 slice"},
{n:"Doughnut (glazed)",cat:"Sweets",gi:76,gl:17,serv:"1 medium"},
{n:"Gulab jamun",cat:"Sweets",gi:75,gl:19,serv:"2 pieces"},
{n:"Jalebi",cat:"Sweets",gi:79,gl:25,serv:"2 pieces"},
{n:"Rasgulla",cat:"Sweets",gi:65,gl:14,serv:"2 pieces"},
{n:"Barfi / burfi",cat:"Sweets",gi:60,gl:16,serv:"1 piece"},
{n:"Besan laddoo",cat:"Sweets",gi:58,gl:15,serv:"1 piece"},
{n:"Motichoor laddoo",cat:"Sweets",gi:68,gl:18,serv:"1 piece"},
{n:"Gajar halwa (carrot)",cat:"Sweets",gi:58,gl:16,serv:"100g"},
{n:"Suji halwa (semolina)",cat:"Sweets",gi:68,gl:22,serv:"100g"},
{n:"Kulfi (plain)",cat:"Sweets",gi:40,gl:8,serv:"1 piece"},
{n:"Potato chips / crisps",cat:"Sweets",gi:56,gl:12,serv:"50g"},
{n:"Namkeen / bhujia",cat:"Sweets",gi:52,gl:9,serv:"30g"},
{n:"Murukku",cat:"Sweets",gi:60,gl:12,serv:"30g"},
{n:"Pretzels",cat:"Sweets",gi:83,gl:19,serv:"30g"},
{n:"Candy / gummy sweets",cat:"Sweets",gi:78,gl:22,serv:"30g"},
{n:"Granola bar",cat:"Sweets",gi:61,gl:13,serv:"1 bar"},
{n:"Protein bar (20g+ protein)",cat:"Sweets",gi:45,gl:10,serv:"1 bar"},
{n:"Waffle (plain)",cat:"Sweets",gi:76,gl:18,serv:"1 medium"},
{n:"Samosa (potato filling)",cat:"Sweets",gi:55,gl:14,serv:"1 piece"},
{n:"Pakora (mixed veg)",cat:"Sweets",gi:50,gl:10,serv:"4 pieces"},
{n:"Kachori",cat:"Sweets",gi:58,gl:14,serv:"1 piece"},
{n:"Pav bhaji",cat:"Sweets",gi:62,gl:18,serv:"1 serving"},
{n:"Vada pav",cat:"Sweets",gi:64,gl:19,serv:"1 piece"},
{n:"Pizza (thin crust, plain)",cat:"Sweets",gi:60,gl:16,serv:"2 slices"},
{n:"Pizza (thick crust)",cat:"Sweets",gi:69,gl:22,serv:"2 slices"},
{n:"Ketchup / tomato sauce",cat:"Condiments",gi:55,gl:3,serv:"1 tbsp"},
{n:"Mayonnaise",cat:"Condiments",gi:0,gl:0,serv:"1 tbsp"},
{n:"Soy sauce",cat:"Condiments",gi:20,gl:0,serv:"1 tbsp"},
{n:"Vinegar (apple cider)",cat:"Condiments",gi:5,gl:0,serv:"1 tbsp"},
{n:"Chutney (mint / pudina)",cat:"Condiments",gi:15,gl:0,serv:"2 tbsp"},
{n:"Chutney (tamarind / imli)",cat:"Condiments",gi:38,gl:4,serv:"1 tbsp"},
{n:"Pickle / achar",cat:"Condiments",gi:10,gl:0,serv:"1 tbsp"},
{n:"Coconut chutney",cat:"Condiments",gi:15,gl:1,serv:"2 tbsp"},
{n:"Olive oil",cat:"Condiments",gi:0,gl:0,serv:"1 tbsp"},
{n:"Coconut oil",cat:"Condiments",gi:0,gl:0,serv:"1 tbsp"},
{n:"Mustard oil",cat:"Condiments",gi:0,gl:0,serv:"1 tbsp"},
];
// EXTRA foods to append to GI_DATABASE
const GI_EXTRA = [
// ── Indian Staples Extended ──
{n:"Sattu (roasted chana flour)",cat:"Legumes",gi:28,gl:6,serv:"3 tbsp"},
{n:"Besan chilla (gram flour pancake)",cat:"Grains",gi:38,gl:8,serv:"2 pieces"},
{n:"Pesarattu (green moong crepe)",cat:"Grains",gi:32,gl:7,serv:"2 pieces"},
{n:"Uttapam (thick dosa)",cat:"Grains",gi:68,gl:16,serv:"1 piece"},
{n:"Sabudana khichdi",cat:"Grains",gi:80,gl:22,serv:"1 bowl"},
{n:"Pongal (rice & lentil)",cat:"Grains",gi:50,gl:12,serv:"1 bowl"},
{n:"Halwa (sooji/semolina)",cat:"Sweets",gi:74,gl:20,serv:"1 serving"},
{n:"Chana masala (canned)",cat:"Legumes",gi:28,gl:8,serv:"1 bowl"},
{n:"Rajma masala (cooked)",cat:"Legumes",gi:24,gl:7,serv:"1 bowl"},
{n:"Tinda (Indian round gourd)",cat:"Vegetables",gi:15,gl:0,serv:"100g"},
{n:"Karela / bitter gourd",cat:"Vegetables",gi:14,gl:0,serv:"100g"},
{n:"Drumstick / moringa",cat:"Vegetables",gi:15,gl:1,serv:"100g"},
{n:"Amla (Indian gooseberry)",cat:"Fruits",gi:15,gl:1,serv:"2 pieces"},
{n:"Kokum",cat:"Fruits",gi:18,gl:1,serv:"small handful"},
{n:"Tamarind (pulp)",cat:"Sweets",gi:65,gl:8,serv:"1 tbsp"},
{n:"Fenugreek leaves (methi)",cat:"Vegetables",gi:10,gl:0,serv:"1 cup"},
{n:"Makhana / fox nuts (roasted)",cat:"Nuts & Seeds",gi:50,gl:8,serv:"1 cup"},
// ── Millets ──
{n:"Jowar (sorghum) roti",cat:"Grains",gi:51,gl:8,serv:"1 medium"},
{n:"Bajra (pearl millet) roti",cat:"Grains",gi:55,gl:9,serv:"1 medium"},
{n:"Ragi (finger millet) roti",cat:"Grains",gi:47,gl:8,serv:"1 medium"},
{n:"Foxtail millet (kangni) cooked",cat:"Grains",gi:50,gl:12,serv:"150g"},
{n:"Little millet (kutki) cooked",cat:"Grains",gi:52,gl:10,serv:"150g"},
{n:"Kodo millet cooked",cat:"Grains",gi:55,gl:11,serv:"150g"},
{n:"Amaranth (rajgira) porridge",cat:"Grains",gi:75,gl:16,serv:"150g"},
{n:"Buckwheat (kuttu) roti",cat:"Grains",gi:54,gl:9,serv:"1 medium"},
// ── Dairy Extended ──
{n:"Paneer bhurji (cooked)",cat:"Dairy",gi:16,gl:1,serv:"100g"},
{n:"Shrikhand (sweet yogurt)",cat:"Dairy",gi:55,gl:14,serv:"100g"},
{n:"Raita (cucumber dahi)",cat:"Dairy",gi:16,gl:2,serv:"100g"},
{n:"Condensed milk",cat:"Dairy",gi:61,gl:28,serv:"2 tbsp"},
{n:"Kefir (plain)",cat:"Dairy",gi:18,gl:2,serv:"200ml"},
{n:"Cottage cheese",cat:"Dairy",gi:10,gl:1,serv:"100g"},
// ── Nuts & Seeds Extended ──
{n:"Sabja seeds (basil seeds, soaked)",cat:"Nuts & Seeds",gi:5,gl:0,serv:"1 tsp"},
{n:"Methi seeds (soaked overnight)",cat:"Nuts & Seeds",gi:10,gl:1,serv:"1 tsp"},
{n:"Hemp seeds",cat:"Nuts & Seeds",gi:15,gl:1,serv:"3 tbsp"},
{n:"Brazil nuts",cat:"Nuts & Seeds",gi:0,gl:0,serv:"30g"},
{n:"Macadamia nuts",cat:"Nuts & Seeds",gi:10,gl:1,serv:"30g"},
{n:"Tahini (sesame paste)",cat:"Nuts & Seeds",gi:20,gl:1,serv:"2 tbsp"},
// ── Fruits Extended ──
{n:"Dragon fruit",cat:"Fruits",gi:48,gl:7,serv:"100g"},
{n:"Passion fruit",cat:"Fruits",gi:30,gl:4,serv:"2 pieces"},
{n:"Starfruit / carambola",cat:"Fruits",gi:35,gl:4,serv:"1 medium"},
{n:"Mulberry",cat:"Fruits",gi:44,gl:5,serv:"100g"},
{n:"Jamun (Indian blackberry)",cat:"Fruits",gi:25,gl:3,serv:"100g"},
{n:"Tamarind fruit",cat:"Fruits",gi:65,gl:8,serv:"30g"},
{n:"Longan",cat:"Fruits",gi:52,gl:8,serv:"100g"},
{n:"Rambutan",cat:"Fruits",gi:49,gl:7,serv:"100g"},
{n:"Feijoa",cat:"Fruits",gi:35,gl:5,serv:"2 medium"},
{n:"Quince",cat:"Fruits",gi:35,gl:5,serv:"1 medium"},
// ── Vegetables Extended ──
{n:"Artichoke",cat:"Vegetables",gi:15,gl:2,serv:"1 medium"},
{n:"Asparagus",cat:"Vegetables",gi:15,gl:1,serv:"80g"},
{n:"Brussels sprouts",cat:"Vegetables",gi:15,gl:1,serv:"80g"},
{n:"Celery",cat:"Vegetables",gi:10,gl:0,serv:"2 stalks"},
{n:"Kale",cat:"Vegetables",gi:10,gl:0,serv:"80g"},
{n:"Swiss chard",cat:"Vegetables",gi:10,gl:0,serv:"80g"},
{n:"Radish / mooli",cat:"Vegetables",gi:15,gl:1,serv:"80g"},
{n:"Turnip (boiled)",cat:"Vegetables",gi:72,gl:5,serv:"150g"},
{n:"Parsnip (boiled)",cat:"Vegetables",gi:52,gl:4,serv:"80g"},
{n:"Leek",cat:"Vegetables",gi:15,gl:2,serv:"80g"},
{n:"Fennel",cat:"Vegetables",gi:15,gl:1,serv:"80g"},
{n:"Watercress",cat:"Vegetables",gi:10,gl:0,serv:"50g"},
{n:"Arugula / rocket",cat:"Vegetables",gi:10,gl:0,serv:"50g"},
{n:"Bok choy",cat:"Vegetables",gi:10,gl:0,serv:"80g"},
{n:"Snow peas",cat:"Vegetables",gi:22,gl:1,serv:"80g"},
{n:"Baby corn",cat:"Vegetables",gi:40,gl:4,serv:"80g"},
{n:"Lotus root",cat:"Vegetables",gi:45,gl:5,serv:"80g"},
{n:"Taro root (cooked)",cat:"Vegetables",gi:53,gl:10,serv:"150g"},
{n:"Cassava / tapioca (boiled)",cat:"Vegetables",gi:94,gl:25,serv:"100g"},
// ── Grains Extended ──
{n:"Millet (proso) cooked",cat:"Grains",gi:70,gl:21,serv:"150g"},
{n:"Teff (injera flatbread)",cat:"Grains",gi:74,gl:13,serv:"1 piece"},
{n:"Freekeh (roasted wheat)",cat:"Grains",gi:43,gl:9,serv:"150g"},
{n:"Farro (cooked)",cat:"Grains",gi:45,gl:10,serv:"150g"},
{n:"Spelt bread",cat:"Grains",gi:54,gl:7,serv:"1 slice"},
{n:"Pumpernickel bread",cat:"Grains",gi:41,gl:5,serv:"1 slice"},
{n:"Rice paper wraps",cat:"Grains",gi:60,gl:9,serv:"2 sheets"},
{n:"Rice vermicelli (cooked)",cat:"Grains",gi:58,gl:12,serv:"180g"},
{n:"Soba noodles (buckwheat)",cat:"Grains",gi:46,gl:14,serv:"180g"},
{n:"Udon noodles",cat:"Grains",gi:55,gl:18,serv:"180g"},
{n:"Shirataki noodles",cat:"Grains",gi:0,gl:0,serv:"200g"},
// ── Protein Extended ──
{n:"Lentil soup (canned)",cat:"Legumes",gi:44,gl:9,serv:"1 bowl"},
{n:"Falafel (baked)",cat:"Legumes",gi:32,gl:8,serv:"4 pieces"},
{n:"Miso soup",cat:"Protein",gi:10,gl:1,serv:"1 bowl"},
{n:"Silken tofu",cat:"Protein",gi:15,gl:1,serv:"100g"},
{n:"Seitan (wheat protein)",cat:"Protein",gi:20,gl:2,serv:"100g"},
// ── Beverages Extended ──
{n:"Kombucha (unsweetened)",cat:"Beverages",gi:10,gl:1,serv:"250ml"},
{n:"Lassi (salt / savoury)",cat:"Beverages",gi:15,gl:2,serv:"250ml"},
{n:"Nimbu pani (no sugar)",cat:"Beverages",gi:5,gl:0,serv:"250ml"},
{n:"Aam panna (raw mango drink)",cat:"Beverages",gi:45,gl:8,serv:"250ml"},
{n:"Thandai (traditional, sweetened)",cat:"Beverages",gi:58,gl:14,serv:"250ml"},
{n:"Jaljeera",cat:"Beverages",gi:10,gl:1,serv:"250ml"},
{n:"Cold coffee with sugar",cat:"Beverages",gi:48,gl:10,serv:"250ml"},
{n:"Protein shake (whey, no sugar)",cat:"Beverages",gi:18,gl:3,serv:"1 scoop + water"},
// ── Sweets Extended ──
{n:"Modak (steamed)",cat:"Sweets",gi:62,gl:14,serv:"2 pieces"},
{n:"Kheer (rice pudding)",cat:"Sweets",gi:65,gl:18,serv:"1 bowl"},
{n:"Payasam",cat:"Sweets",gi:62,gl:16,serv:"1 bowl"},
{n:"Mysore pak",cat:"Sweets",gi:60,gl:14,serv:"1 piece"},
{n:"Halwa (gajar / carrot)",cat:"Sweets",gi:55,gl:12,serv:"1 serving"},
{n:"Peda",cat:"Sweets",gi:58,gl:14,serv:"1 piece"},
{n:"Chakli",cat:"Sweets",gi:52,gl:11,serv:"4 pieces"},
{n:"Murukku",cat:"Sweets",gi:54,gl:12,serv:"4 pieces"},
{n:"Mathri",cat:"Sweets",gi:58,gl:11,serv:"4 pieces"},
{n:"Namak para",cat:"Sweets",gi:60,gl:12,serv:"4 pieces"},
];
if(typeof GI_DATABASE!=='undefined')GI_DATABASE.push(...GI_EXTRA);
