// Glycemic Index & Glycemic Load database
// GI scale: Low 0-55, Medium 56-69, High 70-100
// GL per typical serving: Low 0-10, Medium 11-19, High 20+
const GI_DATABASE = [
// ── Grains, Rice, Bread ──
{n:"White rice (cooked)",cat:"Grains",gi:73,gl:29,serv:"150g"},
{n:"Brown rice (cooked)",cat:"Grains",gi:68,gl:16,serv:"150g"},
{n:"Basmati rice (cooked)",cat:"Grains",gi:58,gl:18,serv:"150g"},
{n:"Cooled/reheated white rice",cat:"Grains",gi:54,gl:18,serv:"150g"},
{n:"Jasmine rice",cat:"Grains",gi:89,gl:35,serv:"150g"},
{n:"Wild rice (cooked)",cat:"Grains",gi:57,gl:18,serv:"150g"},
{n:"Quinoa (cooked)",cat:"Grains",gi:53,gl:13,serv:"150g"},
{n:"White bread",cat:"Grains",gi:75,gl:11,serv:"30g slice"},
{n:"Whole wheat bread",cat:"Grains",gi:69,gl:9,serv:"30g slice"},
{n:"Sourdough bread",cat:"Grains",gi:54,gl:8,serv:"30g slice"},
{n:"Rye bread",cat:"Grains",gi:50,gl:6,serv:"30g slice"},
{n:"Multigrain bread",cat:"Grains",gi:48,gl:7,serv:"30g slice"},
{n:"Naan bread",cat:"Grains",gi:71,gl:24,serv:"90g"},
{n:"Chapati / roti (whole wheat)",cat:"Grains",gi:52,gl:10,serv:"1 medium"},
{n:"Paratha (plain)",cat:"Grains",gi:66,gl:16,serv:"1 medium"},
{n:"Bajra roti (pearl millet)",cat:"Grains",gi:55,gl:9,serv:"1 medium"},
{n:"Jowar roti (sorghum)",cat:"Grains",gi:51,gl:8,serv:"1 medium"},
{n:"Ragi (finger millet) porridge",cat:"Grains",gi:47,gl:9,serv:"1 bowl"},
{n:"Pasta (white, al dente)",cat:"Grains",gi:49,gl:18,serv:"180g"},
{n:"Pasta (whole wheat)",cat:"Grains",gi:42,gl:16,serv:"180g"},
{n:"Noodles (instant/maggi)",cat:"Grains",gi:73,gl:20,serv:"1 packet"},
{n:"Couscous",cat:"Grains",gi:65,gl:23,serv:"150g"},
{n:"Oats (rolled, cooked)",cat:"Grains",gi:55,gl:13,serv:"1 bowl"},
{n:"Instant oatmeal",cat:"Grains",gi:79,gl:21,serv:"1 bowl"},
{n:"Steel cut oats",cat:"Grains",gi:42,gl:11,serv:"1 bowl"},
{n:"Cornflakes",cat:"Grains",gi:81,gl:21,serv:"30g"},
{n:"Muesli (no added sugar)",cat:"Grains",gi:57,gl:10,serv:"30g"},
{n:"Bran flakes",cat:"Grains",gi:74,gl:13,serv:"30g"},
{n:"Idli",cat:"Grains",gi:70,gl:15,serv:"2 pieces"},
{n:"Dosa (plain)",cat:"Grains",gi:77,gl:18,serv:"1 medium"},
{n:"Upma (semolina)",cat:"Grains",gi:65,gl:13,serv:"1 bowl"},
{n:"Poha (flattened rice)",cat:"Grains",gi:67,gl:18,serv:"1 bowl"},
{n:"Khichdi (rice + moong dal)",cat:"Grains",gi:48,gl:13,serv:"1 bowl"},
{n:"Vermicelli (semiya)",cat:"Grains",gi:68,gl:16,serv:"1 bowl"},
{n:"Tortilla (corn)",cat:"Grains",gi:46,gl:10,serv:"2 small"},
{n:"Tortilla (flour)",cat:"Grains",gi:55,gl:13,serv:"1 medium"},
{n:"Rice cakes",cat:"Grains",gi:82,gl:17,serv:"2 cakes"},
{n:"Bagel (plain)",cat:"Grains",gi:72,gl:25,serv:"1 medium"},
{n:"Croissant",cat:"Grains",gi:67,gl:17,serv:"1 medium"},
{n:"Pita bread (white)",cat:"Grains",gi:68,gl:10,serv:"1 piece"},

// ── Legumes & Pulses ──
{n:"Chickpeas / chana (boiled)",cat:"Legumes",gi:28,gl:8,serv:"150g"},
{n:"Kidney beans / rajma (boiled)",cat:"Legumes",gi:24,gl:6,serv:"150g"},
{n:"Black beans (boiled)",cat:"Legumes",gi:30,gl:7,serv:"150g"},
{n:"Lentils / masoor dal (boiled)",cat:"Legumes",gi:29,gl:5,serv:"150g"},
{n:"Moong dal (boiled)",cat:"Legumes",gi:25,gl:4,serv:"150g"},
{n:"Toor dal / arhar dal (boiled)",cat:"Legumes",gi:29,gl:5,serv:"150g"},
{n:"Soybeans (boiled)",cat:"Legumes",gi:16,gl:1,serv:"150g"},
{n:"Green peas (boiled)",cat:"Legumes",gi:51,gl:4,serv:"80g"},
{n:"Baked beans (canned)",cat:"Legumes",gi:48,gl:7,serv:"150g"},
{n:"Hummus",cat:"Legumes",gi:6,gl:1,serv:"2 tbsp"},
{n:"Edamame",cat:"Legumes",gi:18,gl:2,serv:"100g"},
{n:"Tofu",cat:"Legumes",gi:15,gl:1,serv:"100g"},
{n:"Tempeh",cat:"Legumes",gi:15,gl:1,serv:"100g"},
{n:"Black-eyed peas (boiled)",cat:"Legumes",gi:33,gl:7,serv:"150g"},

// ── Fruits ──
{n:"Apple",cat:"Fruits",gi:36,gl:5,serv:"1 medium"},
{n:"Banana (ripe)",cat:"Fruits",gi:51,gl:12,serv:"1 medium"},
{n:"Banana (under-ripe/green)",cat:"Fruits",gi:30,gl:7,serv:"1 medium"},
{n:"Orange",cat:"Fruits",gi:43,gl:5,serv:"1 medium"},
{n:"Grapes",cat:"Fruits",gi:59,gl:9,serv:"120g"},
{n:"Watermelon",cat:"Fruits",gi:76,gl:8,serv:"150g"},
{n:"Mango",cat:"Fruits",gi:51,gl:8,serv:"100g"},
{n:"Pineapple",cat:"Fruits",gi:59,gl:7,serv:"120g"},
{n:"Papaya",cat:"Fruits",gi:60,gl:8,serv:"120g"},
{n:"Pear",cat:"Fruits",gi:38,gl:4,serv:"1 medium"},
{n:"Peach",cat:"Fruits",gi:42,gl:5,serv:"1 medium"},
{n:"Plum",cat:"Fruits",gi:39,gl:5,serv:"2 medium"},
{n:"Strawberries",cat:"Fruits",gi:40,gl:1,serv:"150g"},
{n:"Blueberries",cat:"Fruits",gi:53,gl:5,serv:"150g"},
{n:"Cherries",cat:"Fruits",gi:22,gl:3,serv:"120g"},
{n:"Guava",cat:"Fruits",gi:24,gl:2,serv:"1 medium"},
{n:"Kiwi",cat:"Fruits",gi:50,gl:6,serv:"1 medium"},
{n:"Dates (dried)",cat:"Fruits",gi:42,gl:18,serv:"4 pieces"},
{n:"Raisins",cat:"Fruits",gi:64,gl:28,serv:"60g"},
{n:"Dried apricots",cat:"Fruits",gi:32,gl:9,serv:"60g"},
{n:"Figs (fresh)",cat:"Fruits",gi:35,gl:5,serv:"2 medium"},
{n:"Pomegranate",cat:"Fruits",gi:53,gl:9,serv:"1 medium"},
{n:"Apricot (fresh)",cat:"Fruits",gi:34,gl:3,serv:"3 medium"},
{n:"Cantaloupe / muskmelon",cat:"Fruits",gi:65,gl:5,serv:"120g"},
{n:"Lychee",cat:"Fruits",gi:57,gl:8,serv:"10 pieces"},
{n:"Jackfruit",cat:"Fruits",gi:75,gl:14,serv:"100g"},
{n:"Custard apple / sitaphal",cat:"Fruits",gi:54,gl:11,serv:"100g"},
{n:"Fruit juice (orange, no sugar)",cat:"Fruits",gi:50,gl:12,serv:"250ml"},
{n:"Fruit juice (apple, no sugar)",cat:"Fruits",gi:41,gl:12,serv:"250ml"},
{n:"Dried fig",cat:"Fruits",gi:61,gl:16,serv:"60g"},
{n:"Avocado",cat:"Fruits",gi:15,gl:1,serv:"100g"},

// ── Vegetables ──
{n:"Potato (boiled)",cat:"Vegetables",gi:78,gl:18,serv:"150g"},
{n:"Potato (baked)",cat:"Vegetables",gi:85,gl:26,serv:"150g"},
{n:"Potato (mashed)",cat:"Vegetables",gi:87,gl:17,serv:"150g"},
{n:"Sweet potato (boiled)",cat:"Vegetables",gi:63,gl:17,serv:"150g"},
{n:"French fries",cat:"Vegetables",gi:75,gl:22,serv:"150g"},
{n:"Carrot (raw)",cat:"Vegetables",gi:16,gl:1,serv:"80g"},
{n:"Carrot (cooked)",cat:"Vegetables",gi:39,gl:2,serv:"80g"},
{n:"Beetroot (cooked)",cat:"Vegetables",gi:64,gl:6,serv:"80g"},
{n:"Corn (sweet, boiled)",cat:"Vegetables",gi:52,gl:9,serv:"90g"},
{n:"Pumpkin (boiled)",cat:"Vegetables",gi:75,gl:3,serv:"80g"},
{n:"Tomato",cat:"Vegetables",gi:15,gl:1,serv:"1 medium"},
{n:"Broccoli",cat:"Vegetables",gi:15,gl:1,serv:"80g"},
{n:"Spinach / palak",cat:"Vegetables",gi:15,gl:0,serv:"80g"},
{n:"Cauliflower",cat:"Vegetables",gi:15,gl:1,serv:"80g"},
{n:"Cabbage",cat:"Vegetables",gi:10,gl:0,serv:"80g"},
{n:"Lauki / bottle gourd",cat:"Vegetables",gi:15,gl:1,serv:"100g"},
{n:"Bell pepper / capsicum",cat:"Vegetables",gi:15,gl:1,serv:"80g"},
{n:"Cucumber",cat:"Vegetables",gi:15,gl:0,serv:"100g"},
{n:"Onion",cat:"Vegetables",gi:10,gl:1,serv:"50g"},
{n:"Mushroom",cat:"Vegetables",gi:10,gl:0,serv:"80g"},
{n:"Green beans",cat:"Vegetables",gi:30,gl:1,serv:"80g"},
{n:"Okra / bhindi",cat:"Vegetables",gi:20,gl:1,serv:"80g"},
{n:"Eggplant / baingan",cat:"Vegetables",gi:15,gl:1,serv:"80g"},
{n:"Yam (boiled)",cat:"Vegetables",gi:54,gl:10,serv:"150g"},

// ── Dairy & Alternatives ──
{n:"Whole milk",cat:"Dairy",gi:31,gl:4,serv:"250ml"},
{n:"Skim milk",cat:"Dairy",gi:32,gl:4,serv:"250ml"},
{n:"Plain yogurt / dahi (unsweetened)",cat:"Dairy",gi:14,gl:1,serv:"150g"},
{n:"Greek yogurt (plain)",cat:"Dairy",gi:11,gl:1,serv:"150g"},
{n:"Flavoured yogurt (sweetened)",cat:"Dairy",gi:41,gl:10,serv:"150g"},
{n:"Ice cream (regular)",cat:"Dairy",gi:51,gl:8,serv:"65g"},
{n:"Paneer",cat:"Dairy",gi:14,gl:1,serv:"100g"},
{n:"Cheese (cheddar)",cat:"Dairy",gi:0,gl:0,serv:"30g"},
{n:"Soy milk",cat:"Dairy",gi:34,gl:4,serv:"250ml"},
{n:"Almond milk (unsweetened)",cat:"Dairy",gi:25,gl:1,serv:"250ml"},
{n:"Oat milk",cat:"Dairy",gi:69,gl:9,serv:"250ml"},
{n:"Buttermilk / chaas",cat:"Dairy",gi:15,gl:1,serv:"250ml"},
{n:"Lassi (sweetened)",cat:"Dairy",gi:48,gl:14,serv:"250ml"},

// ── Nuts & Seeds ──
{n:"Almonds",cat:"Nuts & Seeds",gi:0,gl:0,serv:"30g"},
{n:"Walnuts",cat:"Nuts & Seeds",gi:15,gl:1,serv:"30g"},
{n:"Cashews",cat:"Nuts & Seeds",gi:25,gl:3,serv:"30g"},
{n:"Peanuts",cat:"Nuts & Seeds",gi:14,gl:1,serv:"30g"},
{n:"Pistachios",cat:"Nuts & Seeds",gi:15,gl:1,serv:"30g"},
{n:"Chia seeds",cat:"Nuts & Seeds",gi:1,gl:0,serv:"15g"},
{n:"Flaxseeds",cat:"Nuts & Seeds",gi:35,gl:1,serv:"15g"},
{n:"Pumpkin seeds",cat:"Nuts & Seeds",gi:25,gl:1,serv:"30g"},
{n:"Sunflower seeds",cat:"Nuts & Seeds",gi:35,gl:1,serv:"30g"},
{n:"Sesame seeds",cat:"Nuts & Seeds",gi:35,gl:1,serv:"15g"},
{n:"Peanut butter",cat:"Nuts & Seeds",gi:14,gl:1,serv:"2 tbsp"},
{n:"Almond butter",cat:"Nuts & Seeds",gi:8,gl:0,serv:"2 tbsp"},

// ── Sweets & Snacks ──
{n:"Table sugar / sucrose",cat:"Sweets",gi:65,gl:7,serv:"1 tbsp"},
{n:"Honey",cat:"Sweets",gi:61,gl:12,serv:"1 tbsp"},
{n:"Jaggery / gur",cat:"Sweets",gi:84,gl:18,serv:"20g"},
{n:"Maple syrup",cat:"Sweets",gi:54,gl:10,serv:"1 tbsp"},
{n:"Dark chocolate (70%+)",cat:"Sweets",gi:23,gl:4,serv:"30g"},
{n:"Milk chocolate",cat:"Sweets",gi:50,gl:12,serv:"30g"},
{n:"Cookies / biscuits (plain)",cat:"Sweets",gi:64,gl:10,serv:"2 pieces"},
{n:"Cake (sponge, plain)",cat:"Sweets",gi:53,gl:17,serv:"1 slice"},
{n:"Doughnut",cat:"Sweets",gi:76,gl:17,serv:"1 medium"},
{n:"Gulab jamun",cat:"Sweets",gi:75,gl:19,serv:"2 pieces"},
{n:"Jalebi",cat:"Sweets",gi:79,gl:25,serv:"2 pieces"},
{n:"Rasgulla",cat:"Sweets",gi:65,gl:14,serv:"2 pieces"},
{n:"Barfi",cat:"Sweets",gi:60,gl:16,serv:"1 piece"},
{n:"Laddoo (besan)",cat:"Sweets",gi:58,gl:15,serv:"1 piece"},
{n:"Potato chips",cat:"Sweets",gi:56,gl:12,serv:"50g"},
{n:"Popcorn (plain, air-popped)",cat:"Sweets",gi:65,gl:7,serv:"20g"},
{n:"Pretzels",cat:"Sweets",gi:83,gl:19,serv:"30g"},
{n:"Soft drink / cola",cat:"Sweets",gi:63,gl:16,serv:"250ml"},
{n:"Energy drink",cat:"Sweets",gi:73,gl:17,serv:"250ml"},
{n:"Candy / gummy sweets",cat:"Sweets",gi:78,gl:22,serv:"30g"},
{n:"Granola bar",cat:"Sweets",gi:61,gl:13,serv:"1 bar"},
{n:"Waffle",cat:"Sweets",gi:76,gl:18,serv:"1 medium"},
{n:"Pancake (plain)",cat:"Sweets",gi:67,gl:18,serv:"2 medium"},
{n:"Marshmallows",cat:"Sweets",gi:62,gl:15,serv:"30g"},
{n:"Samosa",cat:"Sweets",gi:55,gl:14,serv:"1 piece"},
{n:"Pakora",cat:"Sweets",gi:50,gl:10,serv:"4 pieces"},

// ── Protein / Meat / Fish (negligible carbs → minimal GI relevance, listed as 0) ──
{n:"Chicken breast (cooked)",cat:"Protein",gi:0,gl:0,serv:"100g"},
{n:"Eggs (whole)",cat:"Protein",gi:0,gl:0,serv:"2 eggs"},
{n:"Fish (salmon)",cat:"Protein",gi:0,gl:0,serv:"100g"},
{n:"Fish (tuna)",cat:"Protein",gi:0,gl:0,serv:"100g"},
{n:"Shrimp",cat:"Protein",gi:0,gl:0,serv:"100g"},
{n:"Beef (lean)",cat:"Protein",gi:0,gl:0,serv:"100g"},
{n:"Mutton",cat:"Protein",gi:0,gl:0,serv:"100g"},
{n:"Soy chunks / nutrela (cooked)",cat:"Protein",gi:20,gl:2,serv:"30g dry"},

// ── Beverages ──
{n:"Black coffee (no sugar)",cat:"Beverages",gi:0,gl:0,serv:"1 cup"},
{n:"Green tea (no sugar)",cat:"Beverages",gi:0,gl:0,serv:"1 cup"},
{n:"Black tea (no sugar)",cat:"Beverages",gi:0,gl:0,serv:"1 cup"},
{n:"Chai (with sugar)",cat:"Beverages",gi:35,gl:6,serv:"1 cup"},
{n:"Beer",cat:"Beverages",gi:66,gl:4,serv:"250ml"},
{n:"Red wine",cat:"Beverages",gi:0,gl:0,serv:"150ml"},
{n:"Coconut water",cat:"Beverages",gi:54,gl:5,serv:"250ml"},
{n:"Sports drink",cat:"Beverages",gi:78,gl:13,serv:"250ml"},
];
